using DomainShared.Constant.System;
using SqlSugar;
using System.Text.Json;
using System.Text.Encodings.Web;

namespace Domain.System
{
    /// <summary>
    /// 菜单
    /// </summary>
    [SugarTable("sys_menu")]
    public class Menu : Entity, IAutoGenerated
    {
        /// <summary>
        /// 菜单名称
        /// </summary>
        [SugarColumn(ColumnName = "menu_name", ColumnDescription = "菜单名称", Length = MenuConsts.MaxNameLength,
            IsNullable = false)]
        public string Name { get; set; }

        /// <summary>
        /// 路由地址
        /// </summary>
        [SugarColumn(ColumnName = "menu_path", ColumnDescription = "路由地址", Length = MenuConsts.MaxPathLength)]
        public string Path { get; set; }

        /// <summary>
        /// 菜单图标
        /// </summary>
        [SugarColumn(ColumnName = "menu_icon", ColumnDescription = "菜单图标", Length = MenuConsts.MaxIconLength)]
        public string Icon { get; set; }

        /// <summary>
        /// 父菜单ID
        /// </summary>
        [SugarColumn(ColumnName = "parent_id", ColumnDescription = "父菜单ID")]
        public long? ParentId { get; set; }

        /// <summary>
        /// 显示顺序
        /// </summary>
        [SugarColumn(ColumnName = "sort_order", ColumnDescription = "显示顺序")]
        public int Sort { get; set; }

        /// <summary>
        /// 是否隐藏
        /// </summary>
        [SugarColumn(ColumnName = "is_hidden", ColumnDescription = "是否隐藏")]
        public bool IsHidden { get; set; }

        /// <summary>
        /// 组件路径
        /// </summary>
        [SugarColumn(ColumnName = "component", ColumnDescription = "组件路径", Length = MenuConsts.MaxPathLength)]
        public string Component { get; set; }

        /// <summary>
        /// 路由元数据（JSON格式）
        /// </summary>
        [SugarColumn(ColumnName = "meta", ColumnDescription = "路由元数据", Length = MenuConsts.MaxMetaLength)]
        public string MetaJson { get; set; }

        /// <summary>
        /// 获取路由元数据
        /// </summary>
        [SugarColumn(IsIgnore = true)]
        public MenuMeta Meta
        {
            get
            {
                if (string.IsNullOrEmpty(MetaJson))
                    return new MenuMeta { Title = Name };
                
                try
                {
                    return JsonSerializer.Deserialize<MenuMeta>(MetaJson) ?? new MenuMeta { Title = Name };
                }
                catch
                {
                    return new MenuMeta { Title = Name };
                }
            }
            set
            {
                var jsonOptions = new JsonSerializerOptions
                {
                    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                    WriteIndented = false
                };
                MetaJson = JsonSerializer.Serialize(value, jsonOptions);
            }
        }
    }

    /// <summary>
    /// 菜单元数据
    /// </summary>
    public class MenuMeta
    {
        /// <summary>
        /// 页面标题
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 是否需要认证
        /// </summary>
        public bool RequiresAuth { get; set; } = true;

        /// <summary>
        /// 是否缓存组件
        /// </summary>
        public bool KeepAlive { get; set; } = false;

        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { get; set; }

        /// <summary>
        /// 允许访问的角色
        /// </summary>
        public List<string> Roles { get; set; }
    }
}