using DomainShared.System;
using SqlSugar;

namespace Domain.System
{
    /// <summary>
    /// 菜单
    /// </summary>
    [SugarTable("sys_menu")]
    public class Menu : Entity, IAutoGenerated
    {
        /// <summary>
        /// 菜单名称
        /// </summary>
        [SugarColumn(ColumnName = "menu_name", ColumnDescription = "菜单名称", Length = MenuConsts.MaxNameLength,
            IsNullable = false)]
        public string Name { get; set; }

        /// <summary>
        /// 路由地址
        /// </summary>
        [SugarColumn(ColumnName = "menu_path", ColumnDescription = "路由地址", Length = MenuConsts.MaxPathLength)]
        public string Path { get; set; }

        /// <summary>
        /// 菜单图标
        /// </summary>
        [SugarColumn(ColumnName = "menu_icon", ColumnDescription = "菜单图标", Length = MenuConsts.MaxIconLength)]
        public string Icon { get; set; }

        /// <summary>
        /// 父菜单ID
        /// </summary>
        [SugarColumn(ColumnName = "parent_id", ColumnDescription = "父菜单ID")]
        public long? ParentId { get; set; }

        /// <summary>
        /// 显示顺序
        /// </summary>
        [SugarColumn(ColumnName = "sort_order", ColumnDescription = "显示顺序")]
        public int Sort { get; set; }

        /// <summary>
        /// 是否隐藏
        /// </summary>
        [SugarColumn(ColumnName = "is_hidden", ColumnDescription = "是否隐藏")]
        public bool IsHidden { get; set; }
    }
}