using Domain.Aggregate;
using SqlSugar;

namespace Domain.System
{
    /// <summary>
    /// 岗位
    /// </summary>
    [SugarTable("sys_post")]
    public class Post : Entity, IAutoGenerated
    {
        /// <summary>
        /// 岗位编码
        /// </summary>
        [SugarColumn(ColumnName = "post_code", ColumnDescription = "岗位编码", Length = 64, IsNullable = false)]
        public string Code { get; set; }

        /// <summary>
        /// 岗位名称
        /// </summary>
        [SugarColumn(ColumnName = "post_name", ColumnDescription = "岗位名称", Length = 50, IsNullable = false)]
        public string Name { get; set; }

        /// <summary>
        /// 显示顺序
        /// </summary>
        [SugarColumn(ColumnName = "sort_order", ColumnDescription = "显示顺序")]
        public int Sort { get; set; }

        /// <summary>
        /// 状态（0正常 1停用）
        /// </summary>
        [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0正常 1停用）")]
        public int Status { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        [SugarColumn(ColumnName = "remark", ColumnDescription = "备注", Length = 500)]
        public string Remark { get; set; }
    }
} 