using Domain.Aggregate;
using SqlSugar;

namespace Domain.System;

/// <summary>
/// 角色菜单关联
/// </summary>
[SugarTable("sys_role_menu")]
public class RoleMenu : Entity, IAutoGenerated
{
    /// <summary>
    /// 角色ID
    /// </summary>
    [SugarColumn(ColumnName = "role_id", ColumnDescription = "角色ID")]
    public long RoleId { get; set; }

    /// <summary>
    /// 菜单ID
    /// </summary>
    [SugarColumn(ColumnName = "menu_id", ColumnDescription = "菜单ID")]
    public long MenuId { get; set; }
}