using Domain.Aggregate;
using SqlSugar;

namespace Domain.System;

/// <summary>
/// 角色信息
/// </summary>
[SugarTable("sys_role")]
public class Role : Entity, IAutoGenerated
{
    /// <summary>
    /// 角色名称
    /// </summary>
    [SugarColumn(ColumnName = "name", ColumnDescription = "角色名称")]
    public string Name { get; set; }

    /// <summary>
    /// 角色编码
    /// </summary>
    [SugarColumn(ColumnName = "code", ColumnDescription = "角色编码")]
    public string Code { get; set; }

    /// <summary>
    /// 角色描述
    /// </summary>
    [SugarColumn(ColumnName = "description", ColumnDescription = "角色描述", IsNullable = true)]
    public string Description { get; set; }

    /// <summary>
    /// 状态（0正常 1停用）
    /// </summary>
    [SugarColumn(ColumnName = "status", ColumnDescription = "状态（0正常 1停用）")]
    public int Status { get; set; }
} 