using Domain.Aggregate;
using SqlSugar;

namespace Domain.System;

/// <summary>
/// 用户角色关联
/// </summary>
[SugarTable("sys_user_role")]
public class UserRole : Entity, IAutoGenerated
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID")]
    public long UserId { get; set; }

    /// <summary>
    /// 角色ID
    /// </summary>
    [SugarColumn(ColumnName = "role_id", ColumnDescription = "角色ID")]
    public long RoleId { get; set; }
} 