using Domain.Aggregate;
using SqlSugar;

namespace Domain.System;

/// <summary>
/// 用户岗位关联
/// </summary>
[SugarTable("sys_user_post")]
public class UserPost : Entity, IAutoGenerated
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [SugarColumn(ColumnName = "user_id", ColumnDescription = "用户ID")]
    public long UserId { get; set; }

    /// <summary>
    /// 岗位ID
    /// </summary>
    [SugarColumn(ColumnName = "post_id", ColumnDescription = "岗位ID")]
    public long PostId { get; set; }
} 